name: dev branch sapling extension CI

# Run this workflow on PR into dev branch
on:
  pull_request:
    branches: [ dev ]

jobs:
  build:
  # Run tests on ubuntu linux
    runs-on: ubuntu-latest

    # Run Mocha test suite for sapling extension
    steps:
      - uses: actions/checkout@v2
      - name: Sapling Mocha Tests
        run: |
          cd sapling
          npm install
          npm run test-mocha
